# This file contains the fastlane.tools configuration
# You can find the documentation at https: //docs.fastlane.tools
#
# For a list of all available actions, check out
#
# https: //docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
# https: //docs.fastlane.tools/plugins/available-plugins
#
# Uncomment the line if you want fastlane to automatically update itself
update_fastlane
default_platform(:android)
FLAVOR = ENV["FLAVOR"]
PREFIX = ENV["PREFIX"]

#Display User perform while send to google chat
USER_PERFORM = ENV["USER_PERFORM"]
NAME_BRANCH = ENV["BRANCH_NAME"]
COMMIT_TITLE = ENV["COMMIT_TITLE"]
APP_NAME = ENV["APP_NAME"]
VERSION_NUMBER = ENV["VERSION_CODE"];
VERSION_NAME = ENV["VERSION_NAME"];

ANDROID_BUILD_PATH = "build/app/outputs/flutter-apk/app-#{PREFIX}-release.apk"
IOS_BUILD_PATH = "build/ios/app-#{PREFIX}-release.ipa"
CHANGELOG = File.read("../release-note.txt")
RELEASE_NOTE = File.read("../distribution-note.txt")
IS_ADHOC = ENV["EXPORT_METHOD"] === "ad-hoc"

# These lane without platform is using for sharing lane
desc "Upload build #{FLAVOR} to Diawi and Send to Google Chat"
private_lane :uploadDiawiAndGoogleChat do |values|
	filePath = values[:filePath] 
	platform = values[:platform]
	puts filePath
	puts platform
	diawi(token: ENV['DIAWI_TOKEN'], file: "#{filePath}")
	google_chat(
		webhook: ENV['GOOGLE_CHAT_URL'],
		title: "Build #{platform} #{FLAVOR} by #{USER_PERFORM}",
		description: "#{CHANGELOG}",
		buttonTitle: "DOWNLOAD #{APP_NAME} #{VERSION_NAME} (#{VERSION_NUMBER})",
		section1Title: "Branch #{NAME_BRANCH}",
		section1Description: "Commit #{COMMIT_TITLE}",
		buttonUrl: lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI],
		imageUrl: ENV['IMAGE_URL'],
	)
end

private_lane :uploadAppCenterAndGoogleChat do |values|
	filePath = values[:filePath] 
	platform = values[:platform]
	appName = values[:appName]
	appcenter_upload(
  		file: "#{filePath}",
		app_name: "#{appName}",
  		notify_testers: true,
		destinations: "*",
		release_notes: "#{RELEASE_NOTE}",
		api_token: ENV["APPCENTER_API_TOKEN"]
	)
	google_chat(
		webhook: ENV['GOOGLE_CHAT_URL'],
		title: "AppCenter #{platform} #{FLAVOR}",
		description: "#{RELEASE_NOTE}",
		buttonTitle: "DOWNLOAD #{APP_NAME} #{VERSION_NAME} (#{VERSION_NUMBER})",
		section1Title: "Branch #{NAME_BRANCH}",
		section1Description: "Commit #{COMMIT_TITLE}",
		buttonUrl: "https://appcenter.ms/users/#{ENV["APPCENTER_OWNER_NAME"]}/apps/#{appName}/distribute",
		imageUrl: ENV['IMAGE_URL'],
	)
end

platform :android do
	desc "Build Android #{FLAVOR}"
	lane :buildAndroid do
		gradle(
			task: "clean assemble#{FLAVOR}Release", 
			project_dir: "android/",
			properties: {
				"versionCode" => VERSION_NUMBER,
				"versionName" => VERSION_NAME,
			},
		)
		puts "Finish build"
		uploadDiawiAndGoogleChat(
			filePath: "#{ANDROID_BUILD_PATH}",
			platform: "Android",
		)
	end

	desc "Deploy Android #{FLAVOR} via AppCenter"
	lane :appCenterAndroidDistribute do 
		uploadAppCenterAndGoogleChat(
			filePath: "#{ANDROID_BUILD_PATH}",
			platform: "Android",
			appName: ENV["APPCENTER_ANDROID_APP_NAME"],
		)
	end

	desc "Deploy Android #{FLAVOR} via Firebase"
	lane :firebaseAndroidDistribute do
		firebase_app_distribution(
			app: ENV['FIREBASE_APP_ID'],
			groups: "testers",
			apk_path: "#{ANDROID_BUILD_PATH}",
			firebase_cli_token: ENV['FIREBASE_TOKEN']
		)
	end
end

platform :ios do
	desc "Build iOS #{PREFIX}"
	lane :buildIOS do
		cocoapods(
			podfile: "ios/Podfile",
			silent: true,
			repo_update: true,
		)
		getProvisionAndCertificate
		set_xcconfig_value(
			path: 'ios/Flutter/Generated.xcconfig',
			name: 'FLUTTER_BUILD_NAME',
			value: VERSION_NAME,
		)
		set_xcconfig_value(
			path: 'ios/Flutter/Generated.xcconfig',
			name: 'FLUTTER_BUILD_NUMBER',
			value: VERSION_NUMBER,
		)
		build_app(
			workspace: "ios/Runner.xcworkspace",
			scheme: "#{PREFIX}",
			output_directory: "build/ios",
			output_name: "app-#{PREFIX}-release.ipa",
			export_method: ENV["EXPORT_METHOD"],
			silent: true,
		)
		# export_method enum: [development,ad-hoc,app-store]

		puts "Finish build"
		if IS_ADHOC
		   uploadDiawiAndGoogleChat(
			 filePath: "#{lane_context[SharedValues::IPA_OUTPUT_PATH]}",
			 platform: "IOS",
		   )
		end
	end

	desc "Deploy IOS #{FLAVOR} via TestFlight"
	lane :testFlightDistribute do
		upload_to_testflight(
			submit_beta_review: false,
			skip_waiting_for_build_processing: true,
			ipa: "#{IOS_BUILD_PATH}",
			api_key_path: "fastlane/app_store_connect_token.json",
		)
	end

	desc "Deploy IOS #{FLAVOR} via AppCenter"
	lane :appCenterIOSDistribute do 
		uploadAppCenterAndGoogleChat(
			filePath: "#{IOS_BUILD_PATH}",
			platform: "IOS",
			appName: ENV["APPCENTER_IOS_APP_NAME"],
		)
	end

	desc "Get provision and certificate #{PREFIX} ios"
	private_lane :getProvisionAndCertificate do
		get_certificates(
			generate_apple_certs: false,
			filename: ENV["CER_FILE_NAME"],
			api_key_path: "fastlane/app_store_connect_token.json",
		)
		get_provisioning_profile(
			provisioning_name: ENV["PROVISION_NAME"],
			app_identifier: ENV["IOS_BUNDLE"],
			readonly: true,
			adhoc: IS_ADHOC,
			ignore_profiles_with_different_name: true,
			cert_id: ENV["CER_ID"],
			api_key_path: "fastlane/app_store_connect_token.json",
		)
	end
end